name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: pull_docker
        shell: bash -l {0}
        run: |
          docker pull miyoocfw/toolchain-shared-uclibc:latest

      - uses: addnab/docker-run-action@v3
        with:
          image: miyoocfw/toolchain-shared-uclibc:latest
          options: -w /src -v /home/runner/work/rg35xx-app-DinguxCommander/rg35xx-app-DinguxCommander/src:/src -v /home/runner/work/rg35xx-app-DinguxCommander/rg35xx-app-DinguxCommander/out:/out
          shell: bash -l {0}
          run: |
            make

      - name: tar_release
        shell: bash -l {0}
        run: |
          cp out/DinguxCommander.elf DinguxCommander/
          cp out/j2k.so DinguxCommander/
          cp -r src/res DinguxCommander/
          cp scripts/sw.sh DinguxCommander/
          cp scripts/DinguxCommander.sh DinguxCommander/
          cp scripts/文件管理器.sh DinguxCommander/
          cp scripts/文件管理器.sh ./
          tar -czf release.tar.gz ./DinguxCommander ./Imgs ./文件管理器.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            release.tar.gz
